# Generated by Django 4.1.2 on 2022-10-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCaisse', models.CharField(max_length=100)),
                ('libele', models.CharField(max_length=100)),
                ('typePaiement', models.CharField(max_length=50)),
                ('soldeCaisse', models.IntegerField()),
                ('devise', models.CharField(max_length=50)),
                ('codeJournal', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCategorie', models.CharField(max_length=100)),
                ('libele', models.CharField(max_length=100)),
                ('sens', models.CharField(max_length=100)),
                ('saisieTier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompteG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCaisse', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('libele', models.CharField(max_length=50)),
                ('natureCompte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompteTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCompteTier', models.CharField(max_length=100)),
                ('libele', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('idCompteG', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.compteg')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, verbose_name='matricule')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='prénom')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telephone', models.CharField(max_length=50, verbose_name='téléphone')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('fonction', models.CharField(max_length=200, verbose_name='fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Paramettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSociete', models.CharField(max_length=50)),
                ('operation', models.CharField(max_length=50)),
                ('brouillard', models.CharField(max_length=50)),
                ('employe', models.CharField(max_length=50)),
                ('caisse', models.CharField(max_length=50)),
                ('tiers', models.CharField(max_length=50)),
                ('typeTiers', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=50)),
                ('compteGeneral', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VarSoldeCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('soldeCaisse', models.IntegerField()),
                ('idCaisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.caisse')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeTier', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('localisation', models.CharField(max_length=200)),
                ('idCT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.comptetier')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOperation', models.CharField(max_length=50)),
                ('MSISDN', models.CharField(max_length=50)),
                ('montant', models.IntegerField()),
                ('reference', models.CharField(max_length=50)),
                ('numFacture', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('idCaisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.caisse')),
                ('idCategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.categorie')),
                ('idEmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.employee')),
                ('idTier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.tier')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('idCaisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.caisse')),
                ('idEmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(max_length=50)),
                ('idOperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.operation')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='idCompteG',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.compteg'),
        ),
        migrations.AddField(
            model_name='caisse',
            name='idCompteG',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestCaisse.compteg'),
        ),
    ]
